[tool.poetry]
name = "blackjack-simulation"
version = "0.1.0"
description = ""
authors = ["eyangeric <eyangeric@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
black = "^24.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
